#!/bin/bash

# Pywhl installation script
# Generated by pywhl CLI

set -e  # Exit on error

echo "Starting wheel installation..."

# Check Python installation
if ! command -v python3 &> /dev/null; then
    echo "Error: Python 3 is not installed"
    exit 1
fi

# Check wheel directory
WHEEL_DIR="./wheels"
if [ ! -d "$WHEEL_DIR" ]; then
    echo "Error: Wheel directory not found: $WHEEL_DIR"
    exit 1
fi

# Ensure pip is available
if ! python3 -m pip --version &> /dev/null; then
    echo "Installing pip..."
    python3 -m ensurepip --upgrade
fi

# Install wheels
echo "Installing wheels..."

echo "Installing click..."
# Find and install the wheel for click
for wheel in "$WHEEL_DIR"/click-*.whl; do
    if [ -f "$wheel" ]; then
        python3 -m pip install --user "$wheel"
        break
    fi
done

echo "Installing pytest..."
# Find and install the wheel for pytest
for wheel in "$WHEEL_DIR"/pytest-*.whl; do
    if [ -f "$wheel" ]; then
        python3 -m pip install --user "$wheel"
        break
    fi
done

echo "Installing pandas..."
# Find and install the wheel for pandas
for wheel in "$WHEEL_DIR"/pandas-*.whl; do
    if [ -f "$wheel" ]; then
        python3 -m pip install --user "$wheel"
        break
    fi
done

echo ""
echo "✓ Installation complete!"
echo ""
echo "Installed packages:"
python3 -m pip list | grep -E "(click|pytest|pandas)"